### ISSUE TITLE
Changes Column Headers, Not Names

### ISSUE THREAD

**Issue by elmisback** [praabindhp/Enclone-Encoption#1]
Hey! I think this code changes the column headers, not the names in the data. To change the names you would probably want to iterate over the rows and set the first column for each row to your new anonymized name. This process is called "dataset anonymization". Here's an article describing how it can be done: https://medium.com/district-data-labs/a-practical-guide-to-anonymizing-datasets-with-python-faker-ecf15114c9be

**Comment by praabindhp** [comment]
Yeah Fine, Thank You 👍🏼
